import { Poppins } from "next/font/google";
import { Nav } from "@/components/organisms/Navbar/Nav";
import { Footer } from "@/components";
import "../globals.css";
import { cookies } from "next/headers";
import axios from "axios";

import { Metadata } from "next";
const poppins = Poppins({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Contact Us, Neakhatka.com",
  description: "Generated by create next app",
};

async function getProfileUser() {
  const cookieStore = cookies();
  const session = cookieStore.get("session");
  const sigSession = cookieStore.get("session.sig");

  try {
    const response = await axios.get("http://localhost:4000/v1/users/profile", {
      withCredentials: true, // Include cookies if needed
      headers: {
        Cookie: ` ${session!.name}=${session!.value}; ${sigSession!.name}=${
          sigSession!.value
        }`,
      },
    });

    return response.data;
  } catch (error) {
    console.error(`getProfileUser() Method error: `, error);
    return undefined;
  }
}

export default async function ContactUs({
  children,
}: {
  children: React.ReactNode;
}) {
  const result = await getProfileUser();
  return (
    <html lang="en">
      <link rel="icon" href="/logo.svg" />
      <body className={poppins.className}>
        <Nav userProfile={result} />
        <section>{children}</section>
        <Footer />
      </body>
    </html>
  );
}
